# Generated by Django 3.2.5 on 2021-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
