# Generated by Django 3.2.5 on 2021-07-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0004_alter_property_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('comment', models.TextField()),
                ('owner', models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('posted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.property')),
            ],
        ),
    ]
